---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: indexing
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: indexing
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: indexing
        image: store/server/indexing
        imagePullPolicy: Never
        ports:
          - containerPort: 8080
        resources:
          limits:
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: indexing
spec:
  ports:
  - nodePort: 31000
    port: 8080
    targetPort: 8080
  selector:
    app: indexing
  type: NodePort
