---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: notification
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: notification
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: notification
        image: store/server/notification
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        resources:
          limits:
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: notification
spec:
  ports:
  - nodePort: 31001
    port: 8080
    targetPort: 8080
  selector:
    app: notification
  type: NodePort
