---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: order
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: order
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: order
        image: store/server/order
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        resources:
          limits:
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: order
spec:
  ports:
  - nodePort: 31002
    port: 8080
    targetPort: 8080
  selector:
    app: order
  type: NodePort
