apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:9.6
        imagePullPolicy: IfNotPresent
        env:
        - name: TEST
          value: "256"
        ports:
          - containerPort: 9092
        resources:
          limits:
            memory: 512Mi
